config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :addresses
	root :to => "home#index"
  resources :services
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :services, controller: 'services', only: [:index, :show,:edit, :update, :new, :destroy]

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)
    request.parameters.delete("authenticity_token")
    request.parameters.delete("utf8")
    request.parameters.delete("commit")
    request.parameters.delete("controller")
    request.parameters.delete("action")
    @address.number = Address.last.present? ? Address.last.number.to_i + 1 : 1
    @address.save
    File.open("storage/address_#{@address.number}.json","w") do |f|
      f.write(request.parameters.to_json)
    end
    redirect_to root_path, notice: 'Address was successfully created.'
    # respond_to do |format|
    #   if @address.save
    #     format.html { redirect_to @address, notice: 'Address was successfully created.' }
    #     format.json { render :show, status: :created, location: @address }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @address.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if File.exist?("storage/address_#{@address.number}.json")
        File.delete('storage/address_' + @address.number + '.json')
      end
      if @address.update(address_params)
        request.parameters.delete("authenticity_token")
        request.parameters.delete("utf8")
        request.parameters.delete("commit")
        request.parameters.delete("controller")
        request.parameters.delete("action")
        request.parameters.delete("id")
        request.parameters.delete("_method")
        @address.number = Address.last.present? ? Address.last.number.to_i + 1 : 1
        @address.save
        File.open("storage/address_#{@address.number}.json","w") do |f|
          f.write(request.parameters.to_json)
        end
        format.html { redirect_to root_path, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:address_type, :street_line1, :street_line2, :suburb, :state, :postcode, :start_date, :end_date)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address, local: true) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-2">
    <%= form.label :address_type, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :address_type %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :street_line1, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :street_line1 %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :street_line2, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :street_line2 %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :suburb, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :suburb %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :state , class: "col-sm-3 col-form-label"%>
    <%= form.text_field :state %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :postcode, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :postcode %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :start_date, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :start_date, type: "date" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :end_date, class: "col-sm-3 col-form-label" %>
    <%= form.text_field :end_date, type: "date" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary mb-2 ml-3", style: "color: white;"  %>
  </div>

<% end %>
<style>
  .col-form-label{
    font-size: 10px;
  }
</style>

app/views/addresses/_index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th>Street line1</th>
      <th>Street line2</th>
      <th>Suburb</th>
      <th>State</th>
      <th>Postcode</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.address_type %></td>
        <td><%= address.street_line1 %></td>
        <td><%= address.street_line2 %></td>
        <td><%= address.suburb %></td>
        <td><%= address.state %></td>
        <td><%= address.postcode %></td>
        <td><%= address.start_date %></td>
        <td><%= address.end_date %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', root_path(address: address) %></td>
        <!-- <td><%#= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<style type="text/css">
  table{
    font-size: 10px;
  }
</style>

app/views/addresses/_new.html.erb
<%= render 'addresses/form', address: @address %>

<%#= link_to 'Back', addresses_path, class: "btn btn-primary mb-2", style: "color: white;" %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @address.address_type %>
</p>

<p>
  <strong>Street line1:</strong>
  <%= @address.street_line1 %>
</p>

<p>
  <strong>Street line2:</strong>
  <%= @address.street_line2 %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @address.suburb %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @address.postcode %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @address.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @address.end_date %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>